### ISSUE TITLE
Fail to load when running with norns shield

### ISSUE THREAD

**Issue by DaveCasey** [frederickk/orca#3]
I am extremely new to norns, and to lua, so please forgive me if this is something painfully obvious, but at first glance, it sure looks like there are enough end's in add_note.

### SCRIPT ERROR: load fail
/home/we/dust/code/orca-dev/lib/engines.lua:190: 'end' expected (to close 'function' at line 145) near <eof>
stack traceback:
	/home/we/norns/lua/core/norns.lua:138: in function </home/we/norns/lua/core/norns.lua:138>
	[C]: in function 'dofile'
	/home/we/norns/lua/core/startup.lua:41: in function 'include'
	/home/we/dust/code/orca-dev/orca.lua:45: in main chunk
	[C]: in function 'dofile'
	/home/we/norns/lua/core/script.lua:191: in function </home/we/norns/lua/core/script.lua:191>
	[C]: in function 'xpcall'
	/home/we/norns/lua/core/norns.lua:139: in field 'try'
	/home/we/norns/lua/core/script.lua:191: in function 'core/script.load'
	(...tail calls...)

**Comment by frederickk** [comment]
which branch did you pull `master`? `dev`? or `feature-multiple-engine`? if was any of the latter, you might have caught me committing mid-stream. If you want a stable version I recommend pulling `master`. Or if you're keen to run on the bleeding edge, you could pull `dev` (v.1.4.5).

SSH into Norns and execute this:

```bash
$ cd ~/dust/code
$ git clone https://github.com/frederickk/orca/ orca-dev
```

**Comment by frederickk** [comment]
Closing this issue, for anyone that stumbles across this, please look [here](https://llllllll.co/t/orca/22492/477) for more details and install info.

**Comment by DaveCasey** [comment]
That issue was with the dev branch, probably during the big merge. Syncing to master today works beautifully. Thanks for all of this hard work!!!
